config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   root 'users#index'
#   resources :users, only: %i[index show] do
#     resources :posts, only: %i[index new create show destroy]
#   end

#   resources :posts do
#     resources :comments, only: %i[new create destroy]
#     resources :likes, only: %i[new create destroy]
#     member do
#       post 'like'
#     end

#   end
# end

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :likes, only: %i[new create]
      resources :comments, only: %i[new create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: %i[index new create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comment
  has_many :like, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  enum role: %i[user admin]

  # validates :name, presence: true
  # validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    Post.where(author: self).order(created_at: :desc).first(3)
  end

  def update_posts_counter
    update(posts_counter: posts.count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts
  end

  private

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render plain: 'User not found', status: :not_found
  end
end

app/views/users/index.html.erb
<div class="container">
  <h1 class="mb-4">All Users</h1>
  <% @users.each do |user| %>
    <div class="user-container">
        <div class="user-photo">
          <img src= "<%= user.photo%>" alt= "<%= user.name%>" />
        </div>
        <div class="user-info">
            <h5 class="user-name"><%= link_to user.name, user_path(user),class:'user-link' %></h5>
            <p class="user-post">Posts: <%= user.posts_counter %></p>
        </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

  <%= render 'shared/user_details', user: @user %>

  <h2 class="mt-4">Posts</h2>


   <div class="post-page">
      <% @user.three_recent_posts.each do |post| %>
        <div class="post-card">
            <div class="post-info">
              <%= render 'shared/post_summary', post: post %>
              <p class="card-text"><%= post.text %></p>
            </div>
            
            <div class="com-post">
                <p class="card-text"><strong>Comments:</strong> <%= post.comments_counter %></p>
                <p class="card-text"><strong>Likes:</strong> <%= post.likes_counter %></p>
            </div>
        </div>
      <% end %>

      <%= form_for(@user.posts.build) do |f| %>

    <%= link_to "Create Post", new_post_path(@user), class: "actions" %>

    <% end %>
      <%= link_to "See all posts", user_posts_path(@user), class:"all-posts-btn"%>
    </div>
</div>