config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   root 'users#index'
#   resources :users, only: %i[index show] do
#     resources :posts, only: %i[index new create show destroy]
#   end

#   resources :posts do
#     resources :comments, only: %i[new create destroy]
#     resources :likes, only: %i[new create destroy]
#     member do
#       post 'like'
#     end

#   end
# end

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :likes, only: %i[new create]
      resources :comments, only: %i[new create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: %i[index new create]
        end
      end
    end
  end
end

app/views/shared/_comment.html.erb
<p><strong><%= comment.user.name %>:</strong><%= comment.text %></p>

app/views/shared/_post_details.html.erb
<p><strong>Title:</strong><%= @post.title%></p>
<p><strong>Text:</strong><%= @post.text %></p>

app/views/shared/_post_summary.html.erb
<div class='post-title'>
    <%= link_to post.title, user_post_path(@user, post)%>
</div>

app/views/shared/_user_details.html.erb
<div class="user-detail">
    <div class="user-container">
        <div class="user-photo">
            <%= image_tag(user.photo.url, alt: "#{user.name}'s photo") if user.photo.present?%>
        </div>
        <div class="user-info">
            <h5 class="user-name"><%= link_to user.name, user_path(user),class:'user-link' %></h5>
            <p class="user-post">Posts: <%= user.posts_counter %></p>
        </div>
    </div>
    <div class="bio">
        <p><strong>Bio:</strong></p>
        <p><%= @user.bio%></p>
    </div>
</div>