config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   root 'users#index'
#   resources :users, only: %i[index show] do
#     resources :posts, only: %i[index new create show destroy]
#   end

#   resources :posts do
#     resources :comments, only: %i[new create destroy]
#     resources :likes, only: %i[new create destroy]
#     member do
#       post 'like'
#     end

#   end
# end

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :likes, only: %i[new create]
      resources :comments, only: %i[new create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: %i[index new create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  belongs_to :author, class_name: 'User'
  belongs_to :user, foreign_key: 'author_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :increment_post_counter
  before_validation :initialize_counters

  def create_like(user)
    likes.create(user:)
  end

  def five_recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  def increment_post_counter
    puts 'Incrementing posts counter'
    author.increment!(:posts_counter)
  end

  def all_posts
    Comment.where(post_id: id).order(created_at: :desc)
  end

  def all_comments
    comments.order(created_at: :desc)
  end

  private

  def initialize_counters
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session
  protect_from_forgery with: :exception, except: [:create]

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])

    if @posts
      render json: { status: 'Success', message: 'Bravo!', data: @posts }, status: :ok
    else
      render json: { status: 'Error', message: 'OOPSY Daisy!', errors: @posts.errors }, status: :bad_request
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :comments_counter, :likes_counter)
  end

  skip_before_action :verify_authenticity_token, only: [:create]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: %i[new create]

  load_and_authorize_resource expect:
  %i[index show]

  def index
    set_user
    @user = User.find(params[:user_id])
    @posts = @user.posts
    @index ||= []
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post Created successfully'
    else
      puts @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy
    redirect_to user_posts_path(@user), notice: 'Post deleted successfully.'
  end

  def show
    set_user
    @post = Post.find(params[:id])
  end

  def like
    @post = Post.find(params[:id])
    if current_user.likes.exists?(post: @post)
      redirect_to @post, alert: 'You have already liked this post.'
    else
      current_user.likes.create(post: @post)
      redirect_to @post, notice: 'Post liked!'
    end
  end

  private

  def set_user
    @user = current_user
  rescue ActiveRecord::RecordNotFound
    render plain: 'User not found', status: :not_found
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/_form.html.erb
<!-- app/views/posts/_form.html.erb -->
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="user-detail">
    <div class="user-container">
        <div class="user-photo">
            <% @posts.each do |post| %>
                <%= image_tag(post.user.photo.url, alt: "#{post.user.name}'s photo") if post.user.photo.present? %>
            <% end %> 
        </div>
        <div class="user-info">
            <h5 class="user-name"><%= link_to @user.name, user_path(@user),class:'user-link' %></h5>
            <p class="user-post">Posts: <%= @user.posts_counter %></p>
        </div>
    </div>
</div>


 <div class="post-page">
      <% @posts.each do |post| %>
            <div class="post-card">
                <div class="post-info">
                    <%= render 'shared/post_summary', post: post %>
                    <p class="card-text"><%= post.text %></p>
                </div>
                
                <div class="com-post">
                    <p class="card-text"><strong>Comments:</strong> <%= post.comments_counter %></p>
                    <p class="card-text"><strong>Likes:</strong> <%= post.likes_counter %></p>
                </div>

                <% if can?(:destroy, @post) %>
                     <%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'btn btn-danger' %>
                 <% end %>
            </div>
            <div class="post-com-card">
                <% if post.five_recent_comments.present?%>
                    <% post.five_recent_comments.each do | comment |%>
                        <%= render 'shared/comment', comment: comment%>
                         <% if can?(:destroy, comment) %>
                        <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class: 'btn btn-danger' %>
                    <% end %>
                    <% end %>
                   
                <% else %>
                        <p>No recent commments for this post</p> 
                    <% end %>
            </div>
      <% end %>

      <% if @posts.empty?%>
        <p>User has no posts.</p>
     <% end %>
       
      <%= link_to "Pagenation", user_posts_path(@user), class:"all-posts-btn"%>
    </div>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/show.html.erb
<div class="comments-page">
    <h5><%=  @post.title %> by <%= @user.name%></h5>

    <div class="comments-details">
        <p><strong>Text:</strong><%= @post.text %></p>

        <div class="comments-post">
            <p class="card-text"><strong>Comments:</strong> <%= @post.comments_counter %></p>
            <%= form_for [@post, Like.new], url: post_likes_path(@post) do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit "Like", class: "like-button" %>
            <% end %>
            <p class="card-text"><strong>Likes:</strong> <%= @post.likes_counter %></p>
        </div>
    </div>

    <% if can? :destroy, @post %>
        <%= button_to 'Delete', user_post_path(@post.author), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <% end %>

    <!-- app/views/posts/show.html.erb -->

    <%= link_to "Add Comment", new_post_comment_path(@post), class: "comment-link" %>


    <h2>Comments</h2>
    <% @post.comments.each do | comment |%>
        <%= render 'shared/comment', comment: comment%>
    <% end %>

</div>